### PR TITLE
Fix #43, Remove use of 'dummy' in test code

### LINKED ISSUE #43: Remove redundant use of "dummy" in test code
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
Redundant use of the word "dummy" in some variables/text in the test code. All test variables code are 'dummy' variables - no need to label it as such.

**Code snips**
https://github.com/nasa/HK/blob/71fe47aa17a9ec41c55fd29f634d38a8f962eab2/unit-test/hk_app_tests.c#L1095
https://github.com/nasa/HK/blob/71fe47aa17a9ec41c55fd29f634d38a8f962eab2/unit-test/hk_app_tests.c#L1223

**Expected behavior**
Simplifies test code.

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #43 
'Dummy' removed from test code/text. Redundant.

**Testing performed**
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.

**Expected behavior changes**
No change to behavior. Simplifies test code.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

**Review by chillfig — APPROVED** [review]
Looks good to me!

**Comment by dzbaker** [comment]
@thnkslprpt CCB 6 April 2023: Would you be able to resolve the conflicts?

**Comment by thnkslprpt** [comment]
> @thnkslprpt CCB 6 April 2023: Would you be able to resolve the conflicts?

All clear now @dzbaker

**Comment by dzbaker** [comment]
> > @thnkslprpt CCB 6 April 2023: Would you be able to resolve the conflicts?
> 
> All clear now @dzbaker

Thanks! It looks like a unit test is failing now? Could it be a merge error?

**Comment by thnkslprpt** [comment]
> > > @thnkslprpt CCB 6 April 2023: Would you be able to resolve the conflicts?
> > 
> > 
> > All clear now @dzbaker
> 
> Thanks! It looks like a unit test is failing now? Could it be a merge error?

Ah yes I know what happened. Some of the dummy variables that were changed were moved completely so didn't pop up in the merge but now needs to be removed again. Will have it fixed in a minute.

**Comment by thnkslprpt** [comment]
> > > > @thnkslprpt CCB 6 April 2023: Would you be able to resolve the conflicts?
> > > 
> > > 
> > > All clear now @dzbaker
> > 
> > 
> > Thanks! It looks like a unit test is failing now? Could it be a merge error?
> 
> Ah yes I know what happened. Some of the dummy variables that were changed were moved completely so didn't pop up in the merge but now needs to be removed again. Will have it fixed in a minute.

Working now @dzbaker 
Cheers

**Pull request merged**
